
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "TuyaSmartHomeSdkDemo/app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: 
            cd TuyaSmartHomeSdkDemo/
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/TuyaSmartHomeSdkDemo/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "TuyaSmartHomeSdkDemo/app/build.gradle" }}
      - run:
          name: Assemble App
          command: 
            cd TuyaSmartHomeSdkDemo/
            ./gradlew assembleDebug
      