version: 2.1

jobs:
  build:
    working_directory: ~/TuyaSmartHomeSdkDemo
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Build app
          command: ./tuyasmart_home_android_sdk/TuyaSmartHomeSdkDemo/gradlew assembleDebug
