version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    checkout: post: - cp ./TuyaSmartHomeSdkDemo/local.properties.ci ./TuyaSmartHomeSdkDemo/local.properties
    steps:
      - checkout
      - run:
          name: Build app
          path: ./TuyaSmartHomeSdkDemo
          command: ./gradlew assembleDebug
